### ISSUE TITLE
Move Meteor.subscribe to template instance

### ISSUE THREAD

**Issue by matikucharski** [Lancero/21_todolist#1]
In `task.js`, `user-list.js` and other files you have Meteor.subscribe outside template scope. In result subscriptions are run immediately when code is executed on client instead executing with template. Having subscriptions outside template is considered bad practice.

Move them into onCreated callback like this:

```
  function() {
    this.subscribe('sth');
  }
```

**Comment by Lancero** [comment]
I moved subscriptions to `template.name.onCreated`.  Only one left  `'users'` because I'm not sure where to put it.

Finally I put `users` subscriptions in each template I need it. I hope this is ok

**Comment by matikucharski** [comment]
Great! :tada: 
 Now please create pull request from this issue1 branch.
See below how to do it:
![gifrecord_2016-08-22_120007](https://cloud.githubusercontent.com/assets/4822476/17851050/619e717e-6860-11e6-9df7-5d7aea9c461c.gif)
