### ISSUE TITLE
Add callback to Meteor.call

### ISSUE THREAD

**Issue by matikucharski** [Lancero/21_todolist#2]
In some files (eg: `user-list.js`) you have method calls in events. It is ok. But you have them without callback so you never know if method run fine and without errors. Please add callbacks to all your meteor methods calls like this:

```
  Meteor.call('finishTask', this._id, this.isChecked, function(err, res) {
    if (!err) {
      FlashMessages.sendSuccess('successfully finished task'); //or display nothing (you dont want to inform user about all successful results)
    } else {
      FlashMessages.sendError('There were error while finishing task');
      console.error(err);
    }
  });
```

Making sth like this

```
  Meteor.call('deleteTask', this._id);
  FlashMessages.sendSuccess('Zadanie zostało usunięte');

```

causes displaying success message even before meteor calls method on server so it can be confusing and tells nothing to user.

**Comment by Lancero** [comment]
Done! Please check if it is correct now.

**Comment by matikucharski** [comment]
Nice.
Please create PR (pull request) for this as well from `issue#2` branch as I described in #1
