### ISSUE TITLE
Refactoring code

### ISSUE THREAD

**Issue by matikucharski** [Lancero/21_todolist#3]
- [x] Name files and folers in camelCase style instead of snake_case

As name of JavaScript language is camelCase you should follow this rule with naming files and variables. So `user-list.js` and `new_task.html` became `userList.js` and `newTask.html` respectively.
- [x] move one instance methods to separate files

Also you should keep only one Template in one file so `Template.new_task.events({` and `Template.list.helpers({` should not be in same file as it is in `tasks.js`. They should be with corresponding html files in its own directory.

**Comment by Lancero** [comment]
Done!
